### ISSUE TITLE
CNN-SLAM

### ISSUE THREAD

**Issue by Ntweat** [openMVG/awesome_3DReconstruction_list#11]
Hi 
I recently found an amazing paper on SLAM
CNN-SLAM - http://campar.in.tum.de/Chair/ProjectCNNSLAM

**Comment by pmoulon** [comment]
Feel free to make a PR in order to add the paper reference to the list ;-)

**Comment by Ntweat** [comment]
@pmoulon if you ever think of becoming a professor and are looking for PhD students. Mine will be the first application.
