### ISSUE TITLE
Update link

### ISSUE THREAD

**Issue by weiquanmao** [openMVG/awesome_3DReconstruction_list#15]
Link (http://cvlabwww.epfl.ch/data/multiview/) for data sets 'Dense MVS' is invalid. The data sets can be found at https://icwww.epfl.ch/~marquez/multiview/denseMVS.html now.

**Comment by pmoulon** [comment]
Thx. Fixed by https://github.com/openMVG/awesome_3DReconstruction_list/commit/f31e0ab45cd19502ba928a92fdca9c6491157b79
