### ISSUE TITLE
Scope of the repository

### ISSUE THREAD

**Issue by mihaibujanca** [openMVG/awesome_3DReconstruction_list#2]
I was wondering if the repo is restricted to work dealing with monocular / multiview stereo or if it accepts works based on stereo / structured devices

**Comment by pmoulon** [comment]
Most of the actual work is focused on monocular.
But multiview stereo is accepted.
We must just find how to put in emphasis that there is mono and stereo or structured stuff.

My main matter is to keep the list easy to read, to understand with state of the art stuff

**Comment by mihaibujanca** [comment]
I have a fair amount of good papers, and I'm trying to structure them properly. For now I'm waiting on a reply on the awesome-computer-vision repo, but if anything, I will either contribute to this one or make my own. I'm mostly interested in SLAM using depth sensors, semantic mesh understanding and 3d object boundaries, so that's the kind of stuff I would probably be able to contribute with

**Comment by pmoulon** [comment]
As you saw it, I have structured SfM as "Incremental SfM, Global SfM, Hierarchical SfM,Non Rigid SfM"
We can structure SLAM also in categories "Visual Odometry(cam only), visual-inertial (cam + IMU), RGB+Depth (cam + depth sensors), semantic (object based))

**Comment by mihaibujanca** [comment]
Sure, I think that makes sense. Also, in the long run, I think it's useful to structure the content like
*Topic
    *Year
       *List of papers

Once the list gets really big, it's quite hard to keep the content easy to search

**Comment by pmoulon** [comment]
Please note that papers are already sorted by year (top (old) bottom (recent)) (expect one or two tutorial solution).

Resources are then listed by alphabetical order to be fair.

**Comment by mihaibujanca** [comment]
Oh, I didn't notice that. I tend to keep my lists in reverse chronological order, since I'm usually more interested in the latest work, but I guess chronological order works as well :)

**Comment by pmoulon** [comment]
Just of matter of seeing the things.
I like to see the basis paper that made the new one possible ;-)

**Comment by mihaibujanca** [comment]
Yep, I think that's cool. 
I'll close this issue and will start making a few PRs once I'm off from work

**Comment by pmoulon** [comment]
Please just take care too https://github.com/openMVG/awesome_3DReconstruction_list/blob/master/contributing.md
BTW, the code review tool will be able to help if any problem is spotted ;-)

**Comment by mihaibujanca** [comment]
Sure, already reviewed the guideline :)
