### ISSUE TITLE
COLMAP is now BSD 3-clause

### ISSUE THREAD

**Issue by devernay** [openMVG/awesome_3DReconstruction_list#23]
since version 3.5: 

- https://colmap.github.io/license.html
- https://colmap.github.io/changelog.html

**Comment by pmoulon** [comment]
It is if you build it without CGAL, since CGAL modules does not all have permissive license.
I will update it. Thx.

**Comment by pmoulon** [comment]
https://github.com/openMVG/awesome_3DReconstruction_list/commit/8bdd5f02791b898b69b6b489d85dd9a67098822e

**Comment by devernay** [comment]
Hi,

Colmap is still marked as GPL in the "OpenSource MVS (Multiple View Stereovision)" section

**Comment by pmoulon** [comment]
Updated. Thx!
