### ISSUE TITLE
Shall we include FSSR?

### ISSUE THREAD

**Issue by lywcn** [openMVG/awesome_3DReconstruction_list#29]
Hi, Dr. Moulon

Thank you so much for this AWESOME list! I learnt a lot from it!

I was wondering if the FSSR paper from MVE lib should be included in the surface reconstruction section as well?
[Simon Fuhrmann and Michael Goesele, Floating Scale Surface Reconstruction, In: ACM Transactions on Graphics (Proceedings of ACM SIGGRAPH 2014), Vancouver, Canada, 2014. ](https://www.gcc.tu-darmstadt.de/home/proj/fssr/index.en.jsp)

Thank you!
John

**Comment by pmoulon** [comment]
For the software part FSSR is now a part of MVE that's why I did not listed it directly.

But for sure we can add the paper reference if it is not there. Feel free to do a PR
