### ISSUE TITLE
Patented algorithms column in OpenSource SfM list?

### ISSUE THREAD

**Issue by wzel** [openMVG/awesome_3DReconstruction_list#36]
I think it would make sense to include information which software support evading the patented feature detection and matching algorithms, either by offering a choice of alternative algorithms (actually, none of the six does that, if I'm not wrong; OpenCV does!) or accepting pre-computed data as an additional input (colmap and OpenMVG seem to be capable of that).

**Comment by pmoulon** [comment]
- Sift patent should expire soon.
OpenMVG, OpenSfM have natively multiple alternatives to SIFT for matching.
See here for OpenMVG: https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_ComputeFeatures.cpp#L98
We also have other method implemented but not yet connected to the SfM pipelinehttps://github.com/openMVG/openMVG/tree/develop/src/openMVG/features

As you said OpenMVG and Colmap are flexible and can ingest anything.
OpenMVG also provide a demo to integrate any OpenCV feature detector here https://github.com/openMVG/openMVG/blob/develop/src/software/SfM/main_ComputeFeatures_OpenCV.cpp#L61

Did were you thinking to other patents?

**Comment by wzel** [comment]
Thanks for all the interesting info. I took notice of the `-m` option, but then discovered that it only accepted "SIFT".

In addition to SIFT, there's also SURF, which comes with similar restrictions.

**Comment by pmoulon** [comment]
The `-m` option accepts 4 possibilities (SIFT, SIFT_ANATOMYY, AKAZE_MLDB, AKAZE_LIOP) and then you can plug any of your own feature using the abstraction that is in place.

**Comment by wzel** [comment]
I must have missed that. Thanks.
