### ISSUE TITLE
Add a new open source software for MVS

### ISSUE THREAD

**Issue by stephane-lb** [openMVG/awesome_3DReconstruction_list#4]
Hi Pierre,

Could you add this one to the list : https://github.com/flanggut/smvs

Thanks,

Stephane-lb

( There is also MVIR, but I don't think the source have been released yet )

**Comment by pmoulon** [comment]
Can you provide more information about MVIR?

**Comment by stephane-lb** [comment]
Sure :  http://www.ok.ctrl.titech.ac.jp/~torii/project/mvir/ , they provided binaries but not the sources ...

**Comment by pmoulon** [comment]
The two paper about SMVS and MVIR are already listed.
